import {
  AttachQuestion,
  DropDownQuestion,
  FileExtensions,
  ObjType,
  Question,
  RatingQuestion,
  SelectQuestion,
  SliderQuestion,
  TextualQuestion,
} from "@/6_shared";

export const DirectConvertInitQuestionStates: ObjType<Question> = {
  SELECT: {
    id: 0,
    title: "",
    question: "",
    category: "SELECT",
    subCategory: "MULTI_QUESTION",
    viewOrder: 0,
    required: false,
    questions: [],
    multiple: true,
    responseLimit: 3,
  } as SelectQuestion,
  DESCRIPTIVE: {
    id: 0,
    title: "",
    question: "",
    category: "DESCRIPTIVE",
    subCategory: "TEXTUAL",
    viewOrder: 0,
    required: false,
    answerLimit: 3000,
  } as TextualQuestion,
  EVALUATIVE: {
    id: 0,
    title: "",
    question: "",
    category: "EVALUATIVE",
    subCategory: "RATING",
    viewOrder: 0,
    required: false,
    ratingLimit: 5,
    score: 1,
  } as RatingQuestion,
  EVIDENCE: {
    id: 0,
    title: "",
    question: "",
    category: "EVIDENCE",
    subCategory: "FILE_ATTACH",
    viewOrder: 0,
    required: false,
    attachableAudio: false,
    attachableImage: false,
    attachableVideo: false,
    attachableOthers: false,
    extensions: [] as FileExtensions[],
  } as AttachQuestion,
};

export const InitQuestionStates: ObjType<Question> = {
  MULTI_QUESTION: {
    id: 0,
    title: "",
    question: "",
    category: "SELECT",
    subCategory: "MULTI_QUESTION",
    viewOrder: 0,
    required: false,
    questions: [],
    multiple: true,
    responseLimit: 0,
  } as SelectQuestion,
  DROPDOWN: {
    id: 0,
    title: "",
    question: "",
    category: "SELECT",
    subCategory: "DROPDOWN",
    viewOrder: 0,
    required: false,
    questions: [],
  } as DropDownQuestion,
  TEXTUAL: {
    id: 0,
    title: "",
    question: "",
    category: "DESCRIPTIVE",
    subCategory: "TEXTUAL",
    viewOrder: 0,
    required: false,
    answerLimit: 3000,
  } as TextualQuestion,
  RATING: {
    id: 0,
    title: "",
    question: "",
    category: "EVALUATIVE",
    subCategory: "RATING",
    viewOrder: 0,
    ratingLimit: 5,
    score: 1,
  } as RatingQuestion,
  SLIDER: {
    id: 0,
    title: "",
    question: "",
    category: "EVALUATIVE",
    subCategory: "SLIDER",
    viewOrder: 0,
    min: 0,
    max: 10,
    score: 1,
  } as SliderQuestion,
  FILE_ATTACH: {
    id: 0,
    title: "",
    question: "",
    category: "EVIDENCE",
    subCategory: "FILE_ATTACH",
    viewOrder: 0,
    required: false,
    attachableAudio: false,
    attachableImage: false,
    attachableVideo: false,
    attachableOthers: false,
    extensions: [] as FileExtensions[],
  } as AttachQuestion,
};
